name: Build FModStudio 3p-packages
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  AUTOBUILD_VARIABLES_FILE: ${{github.workspace}}/build-variables/variables

jobs:
  build_matrix:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11,ubuntu-20.04,windows-2022]
        addrsize: [64,32]
        exclude:
          - os: ubuntu-20.04
            addrsize: 32
          - os: macos-11
            addrsize: 32
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        if: runner.os != 'Windows'
        id: py311
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip3 install -r requirements.txt

